### ISSUE TITLE
module 'tqdm' has no attribute 'auto'

### ISSUE THREAD

**Issue by winmoh** [QData/spacetimeformer#73]
when trying to run the command "python train.py spacetimeformer mnist --embed_method spatio-temporal --local_self_attn full --local_cross_attn full --global_self_attn full --global_cross_attn full --run_name mnist_spatiotemporal --context_points 10"

i get this error "

Traceback (most recent call last):
  File "/content/spacetimeformer/spacetimeformer/train.py", line 7, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/base.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/types.py", line 26, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 60, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/bert.py", line 247, in <module>
    def _get_progress_bar(dataloader: DataLoader, verbose: bool = False) -> Union[DataLoader, tqdm.auto.tqdm]:
AttributeError: module 'tqdm' has no attribute 'auto'
"

**Comment by luis-gnz11** [comment]
I've solved it upgrading the torchmetrics package version from 0.5.1 to 0.6.0.

**Comment by elisejiuqizhang** [comment]
sticking with the environment installation command provided by the authors might help avoid the issue? I see that you are using Python 3.10 so likely it is not exactly following the authors' commands (they used Python 3.8)

```
git clone https://github.com/QData/spacetimeformer.git
cd spacetimeformer
conda create -n spacetimeformer python==3.8
conda activate spacetimeformer
pip install -r requirements.txt
pip install -e .
```

**Comment by Sauravak** [comment]
I got the same issue while using python 3.8

**Comment by ziyulu-uw** [comment]
Hey! I also run into the same issue, and I realized that's because I installed the latest pytorch version instead of pytorch 1.11 as suggested by the author "you should follow the official pytorch installation instructions for 1.11". The error goes away when I installed pytorch 1.11. Hope this helps!
